applications = [
    {
      "id": 1,
      "A_Id": "A4374P",
      "Student_Id": "U10000",
      "Internship_Id": "IN123",
      "cover_letter": "Sample cover letter text",
      "introductory_letter": "Sample introductory letter text",
      "curriculum_vitae": "cv_1.pdf",
      "Application_status": "Pending",
      "Application_date": "2023-01-15"
    },
    {
      "id": 2,
      "A_Id": "A5432Q",
      "Student_Id": "U12345",
      "Internship_Id": "IN234",
      "cover_letter": "Another cover letter",
      "introductory_letter": "Another introductory letter",
      "curriculum_vitae": "cv_2.pdf",
      "Application_status": "Approved",
      "Application_date": "2023-02-05"
    },
    {
      "id": 3,
      "A_Id": "A6543R",
      "Student_Id": "U14678",
      "Internship_Id": "IN345",
      "cover_letter": "Yet another cover letter",
      "introductory_letter": "Yet another introductory letter",
      "curriculum_vitae": "cv_3.pdf",
      "Application_status": "Rejected",
      "Application_date": "2023-03-20"
    },
    {
      "id": 4,
      "A_Id": "A7654S",
      "Student_Id": "U18987",
      "Internship_Id": "IN456",
      "cover_letter": "Sample cover letter text",
      "introductory_letter": "Sample introductory letter text",
      "curriculum_vitae": "cv_4.pdf",
      "Application_status": "Pending",
      "Application_date": "2023-04-10"
    },
    {
      "id": 5,
      "A_Id": "A8765T",
      "Student_Id": "U19233",
      "Internship_Id": "IN567",
      "cover_letter": "Another cover letter",
      "introductory_letter": "Another introductory letter",
      "curriculum_vitae": "cv_5.pdf",
      "Application_status": "Approved",
      "Application_date": "2023-05-25"
    },
    {
      "id": 6,
      "A_Id": "A9876U",
      "Student_Id": "U20000",
      "Internship_Id": "IN678",
      "cover_letter": "Yet another cover letter",
      "introductory_letter": "Yet another introductory letter",
      "curriculum_vitae": "cv_6.pdf",
      "Application_status": "Rejected",
      "Application_date": "2023-06-15"
    },
    {
      "id": 7,
      "A_Id": "A10987V",
      "Student_Id": "U21000",
      "Internship_Id": "IN789",
      "cover_letter": "Sample cover letter text",
      "introductory_letter": "Sample introductory letter text",
      "curriculum_vitae": "cv_7.pdf",
      "Application_status": "Pending",
      "Application_date": "2023-07-20"
    },
    {
      "id": 8,
      "A_Id": "A11198W",
      "Student_Id": "U22432",
      "Internship_Id": "IN890",
      "cover_letter": "Another cover letter",
      "introductory_letter": "Another introductory letter",
      "curriculum_vitae": "cv_8.pdf",
      "Application_status": "Approved",
      "Application_date": "2023-08-10"
    },
    {
      "id": 9,
      "A_Id": "A12345X",
      "Student_Id": "U23567",
      "Internship_Id": "IN901",
      "cover_letter": "Yet another cover letter",
      "introductory_letter": "Yet another introductory letter",
      "curriculum_vitae": "cv_9.pdf",
      "Application_status": "Rejected",
      "Application_date": "2023-09-25"
    },
    {
      "id": 10,
      "A_Id": "A23456Y",
      "Student_Id": "U24999",
      "Internship_Id": "IN012",
      "cover_letter": "Sample cover letter text",
      "introductory_letter": "Sample introductory letter text",
      "curriculum_vitae": "cv_10.pdf",
      "Application_status": "Pending",
      "Application_date": "2023-10-15"
    },
    {
      "id": 11,
      "A_Id": "A34567Z",
      "Student_Id": "U25243",
      "Internship_Id": "IN123",
      "cover_letter": "Another cover letter",
      "introductory_letter": "Another introductory letter",
      "curriculum_vitae": "cv_11.pdf",
      "Application_status": "Approved",
      "Application_date": "2023-11-20"
    },
    {
      "id": 12,
      "A_Id": "A45678A",
      "Student_Id": "U26543",
      "Internship_Id": "IN234",
      "cover_letter": "Yet another cover letter",
      "introductory_letter": "Yet another introductory letter",
      "curriculum_vitae": "cv_12.pdf",
      "Application_status": "Rejected",
      "Application_date": "2023-12-10"
    },
    {
      "id": 13,
      "A_Id": "A56789B",
      "Student_Id": "U27321",
      "Internship_Id": "IN345",
      "cover_letter": "Sample cover letter text",
      "introductory_letter": "Sample introductory letter text",
      "curriculum_vitae": "cv_13.pdf",
      "Application_status": "Pending",
      "Application_date": "2024-01-15"
    },
    {
      "id": 14,
      "A_Id": "A67890C",
      "Student_Id": "U28888",
      "Internship_Id": "IN456",
      "cover_letter": "Another cover letter",
      "introductory_letter": "Another introductory letter",
      "curriculum_vitae": "cv_14.pdf",
      "Application_status": "Approved",
      "Application_date": "2024-02-05"
    },
    {
      "id": 15,
      "A_Id": "A78901D",
      "Student_Id": "U29999",
      "Internship_Id": "IN567",
      "cover_letter": "Yet another cover letter",
      "introductory_letter": "Yet another introductory letter",
      "curriculum_vitae": "cv_15.pdf",
      "Application_status": "Rejected",
      "Application_date": "2024-03-20"
    },
    {
      "id": 16,
      "A_Id": "A89012E",
      "Student_Id": "U31111",
      "Internship_Id": "IN678",
      "cover_letter": "Sample cover letter text",
      "introductory_letter": "Sample introductory letter text",
      "curriculum_vitae": "cv_16.pdf",
      "Application_status": "Pending",
      "Application_date": "2024-04-10"
    },
    {
      "id": 17,
      "A_Id": "A90123F",
      "Student_Id": "U32222",
      "Internship_Id": "IN789",
      "cover_letter": "Another cover letter",
      "introductory_letter": "Another introductory letter",
      "curriculum_vitae": "cv_17.pdf",
      "Application_status": "Approved",
      "Application_date": "2024-05-25"
    },
    {
      "id": 18,
      "A_Id": "A01234G",
      "Student_Id": "U33333",
      "Internship_Id": "IN901",
      "cover_letter": "Yet another cover letter",
      "introductory_letter": "Yet another introductory letter",
      "curriculum_vitae": "cv_18.pdf",
      "Application_status": "Rejected",
      "Application_date": "2024-06-15"
    },
    {
      "id": 19,
      "A_Id": "A12345H",
      "Student_Id": "U34444",
      "Internship_Id": "IN012",
      "cover_letter": "Sample cover letter text",
      "introductory_letter": "Sample introductory letter text",
      "curriculum_vitae": "cv_19.pdf",
      "Application_status": "Pending",
      "Application_date": "2024-07-20"
    },
    {
      "id": 20,
      "A_Id": "A23456I",
      "Student_Id": "U35555",
      "Internship_Id": "IN123",
      "cover_letter": "Another cover letter",
      "introductory_letter": "Another introductory letter",
      "curriculum_vitae": "cv_20.pdf",
      "Application_status": "Approved",
      "Application_date": "2024-08-10"
    },
    {
      "id": 21,
      "A_Id": "A34567J",
      "Student_Id": "U10000",
      "Internship_Id": "IN234",
      "cover_letter": "Yet another cover letter",
      "introductory_letter": "Yet another introductory letter",
      "curriculum_vitae": "cv_21.pdf",
      "Application_status": "Pending",
      "Application_date": "2024-09-25"
    },
    {
      "id": 22,
      "A_Id": "A45678K",
      "Student_Id": "U12345",
      "Internship_Id": "IN345",
      "cover_letter": "Sample cover letter text",
      "introductory_letter": "Sample introductory letter text",
      "curriculum_vitae": "cv_22.pdf",
      "Application_status": "Approved",
      "Application_date": "2024-10-15"
    },
    {
      "id": 23,
      "A_Id": "A56789L",
      "Student_Id": "U14678",
      "Internship_Id": "IN456",
      "cover_letter": "Another cover letter",
      "introductory_letter": "Another introductory letter",
      "curriculum_vitae": "cv_23.pdf",
      "Application_status": "Rejected",
      "Application_date": "2024-11-20"
    },
    {
      "id": 24,
      "A_Id": "A67890M",
      "Student_Id": "U18987",
      "Internship_Id": "IN567",
      "cover_letter": "Yet another cover letter",
      "introductory_letter": "Yet another introductory letter",
      "curriculum_vitae": "cv_24.pdf",
      "Application_status": "Pending",
      "Application_date": "2024-12-10"
    },
    {
      "id": 25,
      "A_Id": "A78901N",
      "Student_Id": "U19233",
      "Internship_Id": "IN678",
      "cover_letter": "Sample cover letter text",
      "introductory_letter": "Sample introductory letter text",
      "curriculum_vitae": "cv_25.pdf",
      "Application_status": "Approved",
      "Application_date": "2025-01-15"
    }
  ]
  