internships = [
    {
      "id": 1,
      "IN_Id": "IN123",
      "Company_Id": "C1234",
      "title": "Software Developer Intern",
      "description": "Work on exciting projects as a software developer intern.",
      "requirements": "Must have knowledge of Python, web development, and problem-solving skills.",
      "terms": "3 months internship, full-time, on-site.",
      "duration_type": "months",
      "duration": 3,
      "Schedule": "Fulltime",
      "structure": "Onsite",
      "status": "active",
      "slots_available": 5,
      "application_deadline": "2023-05-15",
      "internship_location": "City, Country",
      "reg_at": "2023-03-01T12:00:00Z",
      "reg_by": "AD",
      "upd_at": "2023-03-01T12:00:00Z",
      "upd_by": "Not yet"
    },
    {
      "id": 2,
      "IN_Id": "IN234",
      "Company_Id": "C5678",
      "title": "Frontend Developer Intern",
      "description": "Join our team as a frontend developer intern and work on modern web applications.",
      "requirements": "Familiarity with HTML, CSS, and JavaScript is required.",
      "terms": "2 months internship, part-time, remote.",
      "duration_type": "months",
      "duration": 2,
      "Schedule": "Part-time",
      "structure": "Remote",
      "status": "active",
      "slots_available": 3,
      "application_deadline": "2023-06-30",
      "internship_location": "Remote",
      "reg_at": "2023-03-01T12:00:00Z",
      "reg_by": "AD",
      "upd_at": "2023-03-01T12:00:00Z",
      "upd_by": "Not yet"
    },
    {
      "id": 3,
      "IN_Id": "IN345",
      "Company_Id": "C9012",
      "title": "Data Analyst Intern",
      "description": "Explore the world of data analysis as an intern with our team.",
      "requirements": "Basic knowledge of data analysis and statistics.",
      "terms": "3 months internship, full-time, on-site.",
      "duration_type": "months",
      "duration": 3,
      "Schedule": "Fulltime",
      "structure": "Onsite",
      "status": "active",
      "slots_available": 2,
      "application_deadline": "2023-04-15",
      "internship_location": "City, Country",
      "reg_at": "2023-03-01T12:00:00Z",
      "reg_by": "AD",
      "upd_at": "2023-03-01T12:00:00Z",
      "upd_by": "Not yet"
    },
    {
      "id": 4,
      "IN_Id": "IN456",
      "Company_Id": "C3456",
      "title": "Marketing Intern",
      "description": "Join our marketing team and gain experience in marketing strategies.",
      "requirements": "Strong communication and marketing skills.",
      "terms": "2 months internship, part-time, remote.",
      "duration_type": "months",
      "duration": 2,
      "Schedule": "Part-time",
      "structure": "Remote",
      "status": "active",
      "slots_available": 4,
      "application_deadline": "2023-05-20",
      "internship_location": "Remote",
      "reg_at": "2023-03-01T12:00:00Z",
      "reg_by": "AD",
      "upd_at": "2023-03-01T12:00:00Z",
      "upd_by": "Not yet"
    },
    {
      "id": 5,
      "IN_Id": "IN567",
      "Company_Id": "C6789",
      "title": "Graphic Design Intern",
      "description": "Join our creative team and work on graphic design projects.",
      "requirements": "Proficiency in graphic design software.",
      "terms": "3 months internship, full-time, on-site.",
      "duration_type": "months",
      "duration": 3,
      "Schedule": "Fulltime",
      "structure": "Onsite",
      "status": "active",
      "slots_available": 3,
      "application_deadline": "2023-06-10",
      "internship_location": "City, Country",
      "reg_at": "2023-03-01T12:00:00Z",
      "reg_by": "AD",
      "upd_at": "2023-03-01T12:00:00Z",
      "upd_by": "Not yet"
    },
    {
      "id": 6,
      "IN_Id": "IN678",
      "Company_Id": "C7890",
      "title": "Content Writer Intern",
      "description": "Join our content team and develop content for various platforms.",
      "requirements": "Strong writing and creative skills.",
      "terms": "2 months internship, part-time, remote.",
      "duration_type": "months",
      "duration": 2,
      "Schedule": "Part-time",
      "structure": "Remote",
      "status": "active",
      "slots_available": 6,
      "application_deadline": "2023-07-15",
      "internship_location": "Remote",
      "reg_at": "2023-03-01T12:00:00Z",
      "reg_by": "AD",
      "upd_at": "2023-03-01T12:00:00Z",
      "upd_by": "Not yet"
    },
    {
      "id": 7,
      "IN_Id": "IN789",
      "Company_Id": "C8901",
      "title": "Finance Intern",
      "description": "Join our finance team and gain experience in financial analysis.",
      "requirements": "Basic knowledge of finance and accounting.",
      "terms": "3 months internship, full-time, on-site.",
      "duration_type": "months",
      "duration": 3,
      "Schedule": "Fulltime",
      "structure": "Onsite",
      "status": "active",
      "slots_available": 2,
      "application_deadline": "2023-08-15",
      "internship_location": "City, Country",
      "reg_at": "2023-03-01T12:00:00Z",
      "reg_by": "AD",
      "upd_at": "2023-03-01T12:00:00Z",
      "upd_by": "Not yet"
    },
    {
      "id": 8,
      "IN_Id": "IN890",
      "Company_Id": "C9012",
      "title": "Human Resources Intern",
      "description": "Join our HR team and assist with HR processes.",
      "requirements": "Strong communication and organizational skills.",
      "terms": "2 months internship, part-time, remote.",
      "duration_type": "months",
      "duration": 2,
      "Schedule": "Part-time",
      "structure": "Remote",
      "status": "active",
      "slots_available": 4,
      "application_deadline": "2023-09-15",
      "internship_location": "Remote",
      "reg_at": "2023-03-01T12:00:00Z",
      "reg_by": "AD",
      "upd_at": "2023-03-01T12:00:00Z",
      "upd_by": "Not yet"
    },
    {
      "id": 9,
      "IN_Id": "IN901",
      "Company_Id": "C0123",
      "title": "Customer Support Intern",
      "description": "Join our customer support team and assist customers with inquiries.",
      "requirements": "Strong communication and problem-solving skills.",
      "terms": "3 months internship, full-time, on-site.",
      "duration_type": "months",
      "duration": 3,
      "Schedule": "Fulltime",
      "structure": "Onsite",
      "status": "active",
      "slots_available": 3,
      "application_deadline": "2023-10-15",
      "internship_location": "City, Country",
      "reg_at": "2023-03-01T12:00:00Z",
      "reg_by": "AD",
      "upd_at": "2023-03-01T12:00:00Z",
      "upd_by": "Not yet"
    },
    {
      "id": 10,
      "IN_Id": "IN012",
      "Company_Id": "C2345",
      "title": "Product Management Intern",
      "description": "Join our product management team and assist with product development.",
      "requirements": "Strong analytical and problem-solving skills.",
      "terms": "2 months internship, part-time, remote.",
      "duration_type": "months",
      "duration": 2,
      "Schedule": "Part-time",
      "structure": "Remote",
      "status": "active",
      "slots_available": 5,
      "application_deadline": "2023-11-15",
      "internship_location": "Remote",
      "reg_at": "2023-03-01T12:00:00Z",
      "reg_by": "AD",
      "upd_at": "2023-03-01T12:00:00Z",
      "upd_by": "Not yet"
    }
  ]
  