export const myusers = [
  {
    "id": 1,
    "U_Id": "U10000",
    "F_name": "John",
    "L_name": "Musisi",
    "email": "john@gmail.com",
    "contact": "123-456-7890",
    "password": "hashed_password_1",
    "user_type": "Student",
    "gender": "male",
    "address": "123 Main St"
  },
  {
    "id": 2,
    "U_Id": "U12345",
    "F_name": "Alice",
    "L_name": "Namubiru",
    "email": "alice.co.org",
    "contact": "987-654-3210",
    "password": "hashed_password_2",
    "user_type": "Company",
    "gender": "female",
    "address": "456 Elm St"
  },
  {
    "id": 3,
    "U_Id": "U14678",
    "F_name": "Bob",
    "L_name": "Ogwal",
    "email": "bob@gmail.com",
    "contact": "555-123-4567",
    "password": "hashed_password_3",
    "user_type": "Student",
    "gender": "male",
    "address": "789 Oak St"
  },
  {
    "id": 4,
    "U_Id": "U18987",
    "F_name": "Jane",
    "L_name": "Nalubega",
    "email": "jane.co.org",
    "contact": "444-999-8888",
    "password": "hashed_password_4",
    "user_type": "Company",
    "gender": "female",
    "address": "567 Pine St"
  },
  {
    "id": 5,
    "U_Id": "U19233",
    "F_name": "Chris",
    "L_name": "Mugabi",
    "email": "chris@gmail.com",
    "contact": "777-111-2222",
    "password": "hashed_password_5",
    "user_type": "Student",
    "gender": "male",
    "address": "321 Cedar St"
  },
  {
    "id": 6,
    "U_Id": "U20000",
    "F_name": "Linda",
    "L_name": "Davis",
    "email": "linda.co.org",
    "contact": "222-888-7777",
    "password": "hashed_password_6",
    "user_type": "Company",
    "gender": "female",
    "address": "876 Birch St"
  },
  {
    "id": 7,
    "U_Id": "U21000",
    "F_name": "Michael",
    "L_name": "Wilson",
    "email": "michael@gmail.com",
    "contact": "333-555-9999",
    "password": "hashed_password_7",
    "user_type": "Student",
    "gender": "male",
    "address": "654 Redwood St"
  },
  {
    "id": 8,
    "U_Id": "U22432",
    "F_name": "Emily",
    "L_name": "Lee",
    "email": "emily.co.org",
    "contact": "666-333-1111",
    "password": "hashed_password_8",
    "user_type": "Company",
    "gender": "female",
    "address": "987 Willow St"
  },
  {
    "id": 9,
    "U_Id": "U23567",
    "F_name": "David",
    "L_name": "Anderson",
    "email": "david@gmail.com",
    "contact": "444-666-7777",
    "password": "hashed_password_9",
    "user_type": "Student",
    "gender": "male",
    "address": "567 Maple St"
  },
  {
    "id": 10,
    "U_Id": "U24999",
    "F_name": "Olivia",
    "L_name": "Harris",
    "email": "olivia.co.org",
    "contact": "888-777-5555",
    "password": "hashed_password_10",
    "user_type": "Company",
    "gender": "female",
    "address": "234 Oakwood St"
  },
  {
    "id": 11,
    "U_Id": "U25243",
    "F_name": "Robert",
    "L_name": "Martin",
    "email": "robert@gmail.com",
    "contact": "777-555-3333",
    "password": "hashed_password_11",
    "user_type": "Student",
    "gender": "male",
    "address": "123 Elmwood St"
  },
  {
    "id": 12,
    "U_Id": "U26543",
    "F_name": "Sophia",
    "L_name": "Young",
    "email": "sophia.co.org",
    "contact": "666-999-1111",
    "password": "hashed_password_12",
    "user_type": "Company",
    "gender": "female",
    "address": "456 Pineview St"
  },
  {
    "id": 13,
    "U_Id": "U27321",
    "F_name": "William",
    "L_name": "Moore",
    "email": "william@gmail.com",
    "contact": "555-777-4444",
    "password": "hashed_password_13",
    "user_type": "Student",
    "gender": "male",
    "address": "654 Willow St"
  },
  {
    "id": 14,
    "U_Id": "U28888",
    "F_name": "Grace",
    "L_name": "Kasaija",
    "email": "grace.co.org",
    "contact": "333-666-1111",
    "password": "hashed_password_14",
    "user_type": "Company",
    "gender": "female",
    "address": "789 Acacia St"
  },
  {
    "id": 15,
    "U_Id": "U29999",
    "F_name": "Daniel",
    "L_name": "Sekajugo",
    "email": "daniel@gmail.com",
    "contact": "222-444-8888",
    "password": "hashed_password_15",
    "user_type": "Student",
    "gender": "male",
    "address": "234 Cedar St"
  },
  {
    "id": 16,
    "U_Id": "U31111",
    "F_name": "Sarah",
    "L_name": "Lubega",
    "email": "sarah.co.org",
    "contact": "111-777-5555",
    "password": "hashed_password_16",
    "user_type": "Company",
    "gender": "female",
    "address": "456 Oak St"
  },
  {
    "id": 17,
    "U_Id": "U32222",
    "F_name": "Peter",
    "L_name": "Ochieng",
    "email": "peter@gmail.com",
    "contact": "777-555-3333",
    "password": "hashed_password_17",
    "user_type": "Student",
    "gender": "male",
    "address": "567 Willow St"
  },
  {
    "id": 18,
    "U_Id": "U33333",
    "F_name": "Amina",
    "L_name": "Nakato",
    "email": "amina.co.org",
    "contact": "666-999-1111",
    "password": "hashed_password_18",
    "user_type": "Company",
    "gender": "female",
    "address": "789 Pineview St"
  },
  {
    "id": 19,
    "U_Id": "U34444",
    "F_name": "Charles",
    "L_name": "Ssewankambo",
    "email": "charles@gmail.com",
    "contact": "555-777-4444",
    "password": "hashed_password_19",
    "user_type": "Student",
    "gender": "male",
    "address": "654 Acacia St"
  },
  {
    "id": 20,
    "U_Id": "U35555",
    "F_name": "Rebecca",
    "L_name": "Nabaggala",
    "email": "rebecca.co.org",
    "contact": "444-666-1111",
    "password": "hashed_password_20",
    "user_type": "Company",
    "gender": "female",
    "address": "123 Cedar St"
  }
]
