"""Initial migration

Revision ID: 0548e1b6d956
Revises: 
Create Date: 2023-10-12 13:21:55.299585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0548e1b6d956'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('A_Id', sa.String(length=2), nullable=False),
    sa.Column('F_name', sa.String(length=20), nullable=False),
    sa.Column('L_name', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=6), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('Contact', sa.String(length=10), nullable=False),
    sa.Column('Address', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=True),
    sa.Column('admin_type', sa.String(length=15), nullable=False),
    sa.Column('profile_image', sa.String(length=200), nullable=False),
    sa.Column('Reg_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('A_Id'),
    sa.UniqueConstraint('admin_type'),
    sa.UniqueConstraint('password')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    # ### end Alembic commands ###
