"""Internship model

Revision ID: 1164c455b543
Revises: db1a2e0d68a4
Create Date: 2023-10-13 13:06:28.656797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1164c455b543'
down_revision = 'db1a2e0d68a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('IN_Id', sa.String(length=5), nullable=False),
    sa.Column('Company_Id', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('terms', sa.Text(), nullable=False),
    sa.Column('duration_type', sa.String(length=6), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('Schedule', sa.String(length=8), nullable=True),
    sa.Column('structure', sa.String(length=6), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('slots_available', sa.Integer(), nullable=False),
    sa.Column('application_deadline', sa.String(length=30), nullable=False),
    sa.Column('internship_location', sa.String(length=50), nullable=False),
    sa.Column('reg_at', sa.String(length=100), nullable=False),
    sa.Column('reg_by', sa.String(length=2), nullable=False),
    sa.Column('upd_at', sa.String(length=100), nullable=False),
    sa.Column('upd_by', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['reg_by'], ['admins.A_Id'], ),
    sa.ForeignKeyConstraint(['upd_by'], ['admins.A_Id'], ),
    sa.PrimaryKeyConstraint('IN_Id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('internships')
    # ### end Alembic commands ###
