"""Interview Question Categories

Revision ID: 44c2483e2b06
Revises: df9c50a91eac
Create Date: 2023-10-13 14:44:48.216939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c2483e2b06'
down_revision = 'df9c50a91eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_code', sa.String(length=8), nullable=False))
        batch_op.create_unique_constraint(None, ['company_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('company_code')

    # ### end Alembic commands ###
