"""Initial migration

Revision ID: 632868faf2b2
Revises: 
Create Date: 2023-10-25 08:08:11.143208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632868faf2b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('A_Id', sa.String(length=2), nullable=False),
    sa.Column('F_name', sa.String(length=20), nullable=False),
    sa.Column('L_name', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=6), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('contact', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('company_code', sa.String(length=8), nullable=False),
    sa.Column('admin_type', sa.String(length=15), nullable=False),
    sa.Column('profile_image', sa.String(length=200), nullable=False),
    sa.Column('reg_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('A_Id'),
    sa.UniqueConstraint('admin_type'),
    sa.UniqueConstraint('company_code'),
    sa.UniqueConstraint('contact'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('password')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('U_Id', sa.String(length=5), nullable=False),
    sa.Column('F_name', sa.String(length=100), nullable=False),
    sa.Column('L_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=6), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('user_type', sa.String(length=10), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('registered_at', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('U_Id'),
    sa.UniqueConstraint('U_Id'),
    sa.UniqueConstraint('contact'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('registered_at'),
    sa.UniqueConstraint('updated_at')
    )
    op.create_table('company_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CP_Id', sa.String(length=5), nullable=False),
    sa.Column('company_contact', sa.String(length=5), nullable=False),
    sa.Column('company_name', sa.String(length=50), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('website', sa.String(length=200), nullable=False),
    sa.Column('linkedIn', sa.String(length=200), nullable=False),
    sa.Column('whatsapp', sa.String(length=15), nullable=False),
    sa.Column('github', sa.String(length=200), nullable=False),
    sa.Column('bitbucket', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('profile_pic', sa.String(length=200), nullable=False),
    sa.Column('reg_at', sa.String(length=100), nullable=False),
    sa.Column('reg_by', sa.String(length=2), nullable=False),
    sa.Column('upd_at', sa.String(length=100), nullable=False),
    sa.Column('upd_by', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['company_contact'], ['users.U_Id'], ),
    sa.ForeignKeyConstraint(['reg_by'], ['admins.A_Id'], ),
    sa.PrimaryKeyConstraint('CP_Id'),
    sa.UniqueConstraint('CP_Id'),
    sa.UniqueConstraint('bitbucket'),
    sa.UniqueConstraint('company_contact'),
    sa.UniqueConstraint('company_name'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('github'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('industry'),
    sa.UniqueConstraint('linkedIn'),
    sa.UniqueConstraint('profile_pic'),
    sa.UniqueConstraint('website'),
    sa.UniqueConstraint('whatsapp')
    )
    op.create_table('frequently_asked_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FAQ_Id', sa.String(length=5), nullable=False),
    sa.Column('U_Id', sa.String(length=5), nullable=True),
    sa.Column('Qn_body', sa.Text(), nullable=False),
    sa.Column('Post_Date', sa.String(length=30), nullable=True),
    sa.Column('Resp_by', sa.String(length=2), nullable=True),
    sa.Column('Resp_Body', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['Resp_by'], ['admins.A_Id'], ),
    sa.ForeignKeyConstraint(['U_Id'], ['users.U_Id'], ),
    sa.PrimaryKeyConstraint('FAQ_Id'),
    sa.UniqueConstraint('Qn_body')
    )
    op.create_table('internships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('IN_Id', sa.String(length=5), nullable=False),
    sa.Column('Company_Id', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('terms', sa.Text(), nullable=False),
    sa.Column('duration_type', sa.String(length=6), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('Schedule', sa.String(length=8), nullable=True),
    sa.Column('structure', sa.String(length=6), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('slots_available', sa.Integer(), nullable=False),
    sa.Column('application_deadline', sa.String(length=30), nullable=False),
    sa.Column('internship_location', sa.String(length=50), nullable=False),
    sa.Column('reg_at', sa.String(length=100), nullable=False),
    sa.Column('reg_by', sa.String(length=2), nullable=False),
    sa.Column('upd_at', sa.String(length=100), nullable=False),
    sa.Column('upd_by', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['reg_by'], ['admins.A_Id'], ),
    sa.PrimaryKeyConstraint('IN_Id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Comm_Id', sa.String(length=7), nullable=False),
    sa.Column('Sender_Id', sa.String(length=5), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('Admin_Id', sa.String(length=2), nullable=True),
    sa.Column('resp_body', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.String(length=30), nullable=True),
    sa.Column('responded_at', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['Admin_Id'], ['admins.A_Id'], ),
    sa.ForeignKeyConstraint(['Sender_Id'], ['users.U_Id'], ),
    sa.PrimaryKeyConstraint('Comm_Id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('question_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('IQC_ID', sa.String(length=7), nullable=False),
    sa.Column('QC_name', sa.String(length=4), nullable=False),
    sa.Column('subfield_Id', sa.String(length=6), nullable=False),
    sa.Column('Education_level', sa.String(length=20), nullable=False),
    sa.Column('reg_at', sa.String(length=100), nullable=False),
    sa.Column('reg_by', sa.String(length=2), nullable=False),
    sa.Column('upd_at', sa.String(length=100), nullable=False),
    sa.Column('upd_by', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['reg_by'], ['admins.A_Id'], ),
    sa.PrimaryKeyConstraint('IQC_ID'),
    sa.UniqueConstraint('QC_name'),
    sa.UniqueConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('R_Id', sa.String(length=6), nullable=False),
    sa.Column('reviewer_id', sa.String(length=5), nullable=True),
    sa.Column('review_text', sa.String(length=200), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('admin_feedback', sa.String(length=200), nullable=True),
    sa.Column('admin_Id', sa.String(length=2), nullable=True),
    sa.Column('made_at', sa.String(length=30), nullable=True),
    sa.Column('upd_at', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['admin_Id'], ['admins.A_Id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.U_Id'], ),
    sa.PrimaryKeyConstraint('R_Id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sub_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SF_Id', sa.String(length=6), nullable=False),
    sa.Column('Title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('FOS', sa.String(length=30), nullable=False),
    sa.Column('sample_image', sa.String(length=100), nullable=False),
    sa.Column('reg_at', sa.String(length=30), nullable=True),
    sa.Column('reg_by', sa.String(length=2), nullable=False),
    sa.Column('upd_at', sa.String(length=30), nullable=True),
    sa.Column('upd_by', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['reg_by'], ['admins.A_Id'], ),
    sa.PrimaryKeyConstraint('SF_Id'),
    sa.UniqueConstraint('Title'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('sample_image')
    )
    op.create_table('tips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('T_Id', sa.String(length=7), nullable=False),
    sa.Column('T_title', sa.String(length=50), nullable=False),
    sa.Column('T_body', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=70), nullable=False),
    sa.Column('Post_Date', sa.String(length=50), nullable=True),
    sa.Column('sample_img', sa.String(length=100), nullable=False),
    sa.Column('reg_by', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['reg_by'], ['admins.A_Id'], ),
    sa.PrimaryKeyConstraint('T_Id'),
    sa.UniqueConstraint('T_body'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ur_Id', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=70), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reg_at', sa.String(length=50), nullable=False),
    sa.Column('reg_by', sa.String(length=2), nullable=True),
    sa.Column('upd_at', sa.String(length=50), nullable=False),
    sa.Column('upd_by', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['reg_by'], ['admins.A_Id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('title'),
    sa.UniqueConstraint('ur_Id')
    )
    op.create_table('interview_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Qn_Id', sa.String(length=9), nullable=False),
    sa.Column('Q_Title', sa.String(length=70), nullable=True),
    sa.Column('Qn_body', sa.Text(), nullable=True),
    sa.Column('IQC_Id', sa.String(length=7), nullable=True),
    sa.Column('reg_at', sa.String(length=100), nullable=False),
    sa.Column('reg_by', sa.String(length=2), nullable=False),
    sa.Column('upd_at', sa.String(length=100), nullable=False),
    sa.Column('upd_by', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['IQC_Id'], ['question_categories.IQC_ID'], ),
    sa.ForeignKeyConstraint(['reg_by'], ['admins.A_Id'], ),
    sa.PrimaryKeyConstraint('Qn_Id'),
    sa.UniqueConstraint('Qn_body'),
    sa.UniqueConstraint('id')
    )
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('SP_Id', sa.String(length=10), nullable=False),
    sa.Column('U_Id', sa.String(length=5), nullable=False),
    sa.Column('S_Name', sa.String(length=60), nullable=False),
    sa.Column('Institution', sa.String(length=60), nullable=False),
    sa.Column('Course', sa.String(length=30), nullable=False),
    sa.Column('Sub_FOS', sa.String(length=6), nullable=False),
    sa.Column('Preferences', sa.Text(), nullable=False),
    sa.Column('Skills', sa.Text(), nullable=False),
    sa.Column('LevelOfEducation', sa.String(length=30), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('Join_EndDate', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('LinkedIn', sa.String(length=80), nullable=False),
    sa.Column('Whatsapp', sa.String(length=10), nullable=False),
    sa.Column('Github', sa.String(length=50), nullable=False),
    sa.Column('Bitbucket', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('profile_pic', sa.String(length=1200), nullable=False),
    sa.Column('reg_at', sa.String(length=20), nullable=True),
    sa.Column('upd_at', sa.String(length=20), nullable=True),
    sa.Column('upd_by', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['Sub_FOS'], ['sub_fields.SF_Id'], ),
    sa.ForeignKeyConstraint(['U_Id'], ['users.U_Id'], ),
    sa.PrimaryKeyConstraint('SP_Id'),
    sa.UniqueConstraint('Bitbucket'),
    sa.UniqueConstraint('Github'),
    sa.UniqueConstraint('LinkedIn'),
    sa.UniqueConstraint('Whatsapp'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('testimonials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('T_ID', sa.String(length=6), nullable=False),
    sa.Column('U_Id', sa.String(length=5), nullable=True),
    sa.Column('Testimaonial_text', sa.Text(), nullable=False),
    sa.Column('Internship_Id', sa.String(length=5), nullable=True),
    sa.Column('reg_at', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['Internship_Id'], ['internships.IN_Id'], ),
    sa.ForeignKeyConstraint(['U_Id'], ['users.U_Id'], ),
    sa.PrimaryKeyConstraint('T_ID'),
    sa.UniqueConstraint('Testimaonial_text'),
    sa.UniqueConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('A_Id', sa.String(length=10), nullable=False),
    sa.Column('Student_Id', sa.String(length=10), nullable=True),
    sa.Column('Internship_Id', sa.String(length=5), nullable=True),
    sa.Column('cover_letter', sa.String(length=200), nullable=False),
    sa.Column('introductory_letter', sa.String(length=200), nullable=False),
    sa.Column('curriculum_vitae', sa.String(length=200), nullable=False),
    sa.Column('Application_status', sa.String(length=10), nullable=False),
    sa.Column('Application_date', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['Internship_Id'], ['internships.IN_Id'], ),
    sa.ForeignKeyConstraint(['Student_Id'], ['student_profiles.SP_Id'], ),
    sa.PrimaryKeyConstraint('A_Id'),
    sa.UniqueConstraint('cover_letter'),
    sa.UniqueConstraint('curriculum_vitae'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('introductory_letter')
    )
    op.create_table('saved_internship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SIM_ID', sa.String(length=10), nullable=False),
    sa.Column('Student_Id', sa.String(length=6), nullable=True),
    sa.Column('Internship_Id', sa.String(length=5), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=True),
    sa.Column('Made_at', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['Internship_Id'], ['internships.IN_Id'], ),
    sa.ForeignKeyConstraint(['Student_Id'], ['student_profiles.SP_Id'], ),
    sa.PrimaryKeyConstraint('SIM_ID'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_internship')
    op.drop_table('applications')
    op.drop_table('testimonials')
    op.drop_table('student_profiles')
    op.drop_table('interview_questions')
    op.drop_table('user_roles')
    op.drop_table('tips')
    op.drop_table('sub_fields')
    op.drop_table('reviews')
    op.drop_table('question_categories')
    op.drop_table('messages')
    op.drop_table('internships')
    op.drop_table('frequently_asked_questions')
    op.drop_table('company_profiles')
    op.drop_table('users')
    op.drop_table('admins')
    # ### end Alembic commands ###
