"""Sub fields

Revision ID: 84f1e08f3c73
Revises: c69c8786ba37
Create Date: 2023-10-13 10:49:39.920229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84f1e08f3c73'
down_revision = 'c69c8786ba37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SF_Id', sa.String(length=6), nullable=False),
    sa.Column('Title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('FOS', sa.String(length=30), nullable=False),
    sa.Column('sample_image', sa.String(length=100), nullable=False),
    sa.Column('reg_at', sa.String(length=30), nullable=True),
    sa.Column('reg_by', sa.String(length=2), nullable=False),
    sa.Column('upd_at', sa.String(length=30), nullable=True),
    sa.Column('upd_by', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['reg_by'], ['admins.A_Id'], ),
    sa.ForeignKeyConstraint(['upd_by'], ['admins.A_Id'], ),
    sa.PrimaryKeyConstraint('SF_Id'),
    sa.UniqueConstraint('Title'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('sample_image')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.create_unique_constraint(None, ['description'])
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)

    op.drop_table('sub_fields')
    # ### end Alembic commands ###
