"""image storage

Revision ID: 8a864c9f4995
Revises: 632868faf2b2
Create Date: 2023-10-25 08:33:47.484396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a864c9f4995'
down_revision = '632868faf2b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('profile_image',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('profile_image',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
