"""Initial migrations

Revision ID: c3b8496ffc1a
Revises: 
Create Date: 2023-10-17 18:28:23.415228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b8496ffc1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ur_Id', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=70), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reg_at', sa.String(length=50), nullable=False),
    sa.Column('reg_by', sa.Integer(), nullable=True),
    sa.Column('upd_at', sa.String(length=50), nullable=False),
    sa.Column('upd_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reg_by'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['upd_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('title'),
    sa.UniqueConstraint('ur_Id')
    )
    op.create_table('interview_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Qn_Id', sa.String(length=9), nullable=False),
    sa.Column('Q_Title', sa.String(length=70), nullable=True),
    sa.Column('Qn_body', sa.Text(), nullable=True),
    sa.Column('IQC_Id', sa.String(length=7), nullable=True),
    sa.Column('reg_at', sa.String(length=100), nullable=False),
    sa.Column('reg_by', sa.String(length=2), nullable=False),
    sa.Column('upd_at', sa.String(length=100), nullable=False),
    sa.Column('upd_by', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['IQC_Id'], ['question_categories.IQC_ID'], ),
    sa.ForeignKeyConstraint(['reg_by'], ['admins.A_Id'], ),
    sa.ForeignKeyConstraint(['upd_by'], ['admins.A_Id'], ),
    sa.PrimaryKeyConstraint('Qn_Id'),
    sa.UniqueConstraint('Qn_body'),
    sa.UniqueConstraint('id')
    )
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('SP_Id', sa.String(length=10), nullable=False),
    sa.Column('U_Id', sa.String(length=5), nullable=False),
    sa.Column('S_Name', sa.String(length=60), nullable=False),
    sa.Column('Institution', sa.String(length=60), nullable=False),
    sa.Column('Course', sa.String(length=30), nullable=False),
    sa.Column('Sub_FOS', sa.String(length=6), nullable=False),
    sa.Column('Preferences', sa.Text(), nullable=False),
    sa.Column('Skills', sa.Text(), nullable=False),
    sa.Column('LevelOfEducation', sa.String(length=30), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('Join_EndDate', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('LinkedIn', sa.String(length=80), nullable=False),
    sa.Column('Whatsapp', sa.String(length=10), nullable=False),
    sa.Column('Github', sa.String(length=50), nullable=False),
    sa.Column('Bitbucket', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('profile_pic', sa.String(length=1200), nullable=False),
    sa.Column('reg_at', sa.String(length=20), nullable=True),
    sa.Column('reg_by', sa.String(length=5), nullable=True),
    sa.Column('upd_at', sa.String(length=20), nullable=True),
    sa.Column('upd_by', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['Sub_FOS'], ['sub_fields.SF_Id'], ),
    sa.ForeignKeyConstraint(['U_Id'], ['users.U_Id'], ),
    sa.ForeignKeyConstraint(['reg_by'], ['users.U_Id'], ),
    sa.ForeignKeyConstraint(['upd_by'], ['users.U_Id'], ),
    sa.PrimaryKeyConstraint('SP_Id'),
    sa.UniqueConstraint('Bitbucket'),
    sa.UniqueConstraint('Github'),
    sa.UniqueConstraint('LinkedIn'),
    sa.UniqueConstraint('Whatsapp'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('testimonials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('T_ID', sa.String(length=6), nullable=False),
    sa.Column('U_Id', sa.String(length=5), nullable=True),
    sa.Column('Testimaonial_text', sa.Text(), nullable=False),
    sa.Column('Internship_Id', sa.String(length=5), nullable=True),
    sa.Column('reg_at', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['Internship_Id'], ['internships.IN_Id'], ),
    sa.ForeignKeyConstraint(['U_Id'], ['users.U_Id'], ),
    sa.PrimaryKeyConstraint('T_ID'),
    sa.UniqueConstraint('Testimaonial_text'),
    sa.UniqueConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('A_Id', sa.String(length=10), nullable=False),
    sa.Column('Student_Id', sa.String(length=10), nullable=True),
    sa.Column('Internship_Id', sa.String(length=5), nullable=True),
    sa.Column('cover_letter', sa.String(length=200), nullable=False),
    sa.Column('introductory_letter', sa.String(length=200), nullable=False),
    sa.Column('curriculum_vitae', sa.String(length=200), nullable=False),
    sa.Column('Application_status', sa.String(length=10), nullable=False),
    sa.Column('Application_date', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['Internship_Id'], ['internships.IN_Id'], ),
    sa.ForeignKeyConstraint(['Student_Id'], ['student_profiles.SP_Id'], ),
    sa.PrimaryKeyConstraint('A_Id'),
    sa.UniqueConstraint('cover_letter'),
    sa.UniqueConstraint('curriculum_vitae'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('introductory_letter')
    )
    op.create_table('saved_internship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SIM_ID', sa.String(length=10), nullable=False),
    sa.Column('Student_Id', sa.String(length=6), nullable=True),
    sa.Column('Internship_Id', sa.String(length=5), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=True),
    sa.Column('Made_at', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['Internship_Id'], ['internships.IN_Id'], ),
    sa.ForeignKeyConstraint(['Student_Id'], ['student_profiles.SP_Id'], ),
    sa.PrimaryKeyConstraint('SIM_ID'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_internship')
    op.drop_table('applications')
    op.drop_table('testimonials')
    op.drop_table('student_profiles')
    op.drop_table('interview_questions')
    op.drop_table('user_roles')
    # ### end Alembic commands ###
