"""User Roles model

Revision ID: c69c8786ba37
Revises: 94ded614ce7a
Create Date: 2023-10-13 08:22:38.301553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c69c8786ba37'
down_revision = '94ded614ce7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('ur_Id', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=70), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reg_at', sa.String(length=50), nullable=False),
    sa.Column('reg_by', sa.String(length=3), nullable=True),
    sa.Column('upd_at', sa.String(length=50), nullable=False),
    sa.Column('upd_by', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['reg_by'], ['admins.A_Id'], ),
    sa.ForeignKeyConstraint(['upd_by'], ['admins.A_Id'], ),
    sa.PrimaryKeyConstraint('ur_Id'),
    sa.UniqueConstraint('title'),
    sa.UniqueConstraint('ur_Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    # ### end Alembic commands ###
