"""Users and company

Revision ID: db1a2e0d68a4
Revises: 84f1e08f3c73
Create Date: 2023-10-13 12:04:51.899049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1a2e0d68a4'
down_revision = '84f1e08f3c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('U_Id', sa.String(length=5), nullable=False),
    sa.Column('F_name', sa.String(length=100), nullable=False),
    sa.Column('L_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=6), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('user_type', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('registered_at', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('U_Id'),
    sa.UniqueConstraint('U_Id'),
    sa.UniqueConstraint('contact'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('registered_at'),
    sa.UniqueConstraint('updated_at')
    )
    op.create_table('company_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CP_Id', sa.String(length=5), nullable=False),
    sa.Column('company_contact', sa.String(length=5), nullable=False),
    sa.Column('company_name', sa.String(length=50), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('website', sa.String(length=200), nullable=False),
    sa.Column('linkedIn', sa.String(length=200), nullable=False),
    sa.Column('whatsapp', sa.String(length=15), nullable=False),
    sa.Column('github', sa.String(length=200), nullable=False),
    sa.Column('bitbucket', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('profile_pic', sa.String(length=200), nullable=False),
    sa.Column('reg_at', sa.String(length=100), nullable=False),
    sa.Column('reg_by', sa.String(length=2), nullable=False),
    sa.Column('upd_at', sa.String(length=100), nullable=False),
    sa.Column('upd_by', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['company_contact'], ['users.U_Id'], ),
    sa.ForeignKeyConstraint(['reg_by'], ['admins.A_Id'], ),
    sa.ForeignKeyConstraint(['upd_by'], ['admins.A_Id'], ),
    sa.PrimaryKeyConstraint('CP_Id'),
    sa.UniqueConstraint('CP_Id'),
    sa.UniqueConstraint('bitbucket'),
    sa.UniqueConstraint('company_contact'),
    sa.UniqueConstraint('company_name'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('github'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('industry'),
    sa.UniqueConstraint('linkedIn'),
    sa.UniqueConstraint('profile_pic'),
    sa.UniqueConstraint('website'),
    sa.UniqueConstraint('whatsapp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
