"""Interview Question Categories

Revision ID: df9c50a91eac
Revises: 1164c455b543
Create Date: 2023-10-13 14:29:32.137303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9c50a91eac'
down_revision = '1164c455b543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('IQC_ID', sa.String(length=7), nullable=False),
    sa.Column('QC_name', sa.String(length=4), nullable=False),
    sa.Column('subfield_Id', sa.String(length=6), nullable=False),
    sa.Column('Education_level', sa.String(length=20), nullable=False),
    sa.Column('reg_at', sa.String(length=100), nullable=False),
    sa.Column('reg_by', sa.String(length=2), nullable=False),
    sa.Column('upd_at', sa.String(length=100), nullable=False),
    sa.Column('upd_by', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['reg_by'], ['admins.A_Id'], ),
    sa.ForeignKeyConstraint(['upd_by'], ['admins.A_Id'], ),
    sa.PrimaryKeyConstraint('IQC_ID'),
    sa.UniqueConstraint('QC_name'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_categories')
    # ### end Alembic commands ###
