"""time

Revision ID: e2d6e79fbd8d
Revises: b52a12f9a095
Create Date: 2023-10-26 08:54:44.280258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d6e79fbd8d'
down_revision = 'b52a12f9a095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('registered_at')
        batch_op.drop_index('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('updated_at', ['updated_at'], unique=False)
        batch_op.create_index('registered_at', ['registered_at'], unique=False)

    # ### end Alembic commands ###
